django_quiz/content/urls.py
# Django
from django.conf.urls import url

# Local
from .views import AnswerCreateView, LessonDetailView, LessonListView 
from .views import QuestionDetailView, QuizAnswerListView, QuizDetailView

urlpatterns = [
    url(r'^lesson/$', LessonListView.as_view(), name='lesson_list'), 
    url(r'^lesson/(?P<pk>\d+)/$', LessonDetailView.as_view(), 
        name='lesson_detail'), 
    url(r'^quiz/(?P<pk>\d+)/$', QuizDetailView.as_view(), name='quiz_detail'), 
    url(r'^quiz/(?P<pk>\d+)/answer/$', QuizAnswerListView.as_view(), 
        name='quiz_answer_list'), 
    url(r'^question/(?P<pk>\d+)/$', QuestionDetailView.as_view(), 
        name='question_detail'), 
    url(r'^question/(?P<pk>\d+)/answer/create/$', AnswerCreateView.as_view(), 
        name='answer_create')
]

django_quiz/urls.py
# Django
from django.conf.urls import include, url
from django.contrib import admin

# Local
from .views import HomepageView

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'), 
    url(r'^admin/', admin.site.urls), 
    url(r'^content/', include('django_quiz.content.urls'))
]

django_quiz/common/models.py
# Django
from django.db import models

class Tag(models.Model):
    name = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_quiz/content/models.py
# Django
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext as _

# Local
from django_quiz.common.models import Tag

class Lesson(models.Model):
    title = models.CharField(max_length=50, unique=True)
    body = models.TextField(max_length=2000)
    tags = models.ManyToManyField(Tag, related_name='%(class)s')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson_detail', args=(self.id,))

class Quiz(models.Model):
    lesson = models.ForeignKey(Lesson)
    title = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('lesson', 'title')
        )
        verbose_name_plural = _('quizzes')

    def __str__(self):
        return '{0}: {1}'.format(self.lesson, self.title)

    def get_absolute_url(self):
        return reverse('quiz_detail', args=(self.id,))

    def get_unanswered_questions(self, user):
        user_answers = Answer.objects.filter(user=user)
        question_ids = [answer.question.id for answer in user_answers]
        return self.question_set.exclude(id__in=question_ids)

    def get_score(self, user):
        correct_answer_count = Answer.objects.filter(user=user, 
            question__quiz=self, is_correct=True).count()
        question_count = Question.objects.filter(quiz=self).count()
        if question_count == 0:
            return 'N/A'
        return '{0:.2%}'.format(correct_answer_count / question_count)


class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    body = models.TextField(max_length=1000)
    correct_answer = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('quiz', 'body')
        )

    def __str__(self):
        return self.body

    def get_user_answer(self, user):
        try:
            answer = self.answer_set.get(user=user, question=self)
        except ObjectDoesNotExist as e:
            answer = Answer.objects.none()

        return answer

class Answer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    choice = models.BooleanField(default=False, 
        verbose_name='True or False?', help_text='Checked=True')
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'question')
        )

    def __str__(self):
        return '{0}'.format(self.choice)

    def save(self, *args, **kwargs):
        self.is_correct = self.choice == self.question.correct_answer
        super().save(*args, **kwargs)

django_quiz/content/forms.py
# Django
from django.forms import ModelForm

# Local
from .models import Answer

class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ('choice',)

django_quiz/common/views.py
from django.shortcuts import render

# Create your views here.

django_quiz/content/views.py
# Django
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, CreateView, ListView

# Local
from .forms import AnswerForm
from .models import Answer, Lesson, Question, Quiz
from django_quiz.mixins import LoginRequiredMixin

class LessonListView(LoginRequiredMixin, ListView):
    model = Lesson
    template_name = 'content/lessons/list.html'

class LessonDetailView(LoginRequiredMixin, DetailView):
    model = Lesson
    template_name = 'content/lessons/detail.html'

class QuizDetailView(LoginRequiredMixin, DetailView):
    model = Quiz
    template_name = 'content/quizzes/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        quiz = self.get_object()
        unanswered_questions = quiz.get_unanswered_questions(self.request.user)
        context['done'] = unanswered_questions.count() == 0
        return context

class QuizAnswerListView(LoginRequiredMixin, ListView):
    model = Answer
    template_name = 'content/quizzes/answers/list.html'

    def get_queryset(self):
        self.quiz = Quiz.objects.get(id=self.kwargs['pk'])
        return Answer.objects.filter(user=self.request.user, 
            question__quiz=self.quiz)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['score'] = self.quiz.get_score(self.request.user)
        return context

class QuestionDetailView(LoginRequiredMixin, DetailView):
    model = Question
    template_name = 'content/questions/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        user_answer = self.get_object().get_user_answer(self.request.user)
        if user_answer:
            context['already_answered'] = True
        else:
            context['already_answered'] = False
            context['form'] = AnswerForm
        return context

class AnswerCreateView(LoginRequiredMixin, CreateView):
    model = Answer
    template = 'content/answers/create.html'
    form_class = AnswerForm

    def get_success_url(self):
        quiz = self.get_object().question.quiz
        questions = Question.objects.filter(quiz=quiz)
        for question in questions:
            if not question.get_user_answer(self.request.user):
                return question.get_absolute_url()

        return reverse('lesson_list')

    def form_valid(self, form):
        if form.is_valid():
            form.instance.user = self.request.user
            question = Question.objects.get(id=self.kwargs['pk'])
            form.instance.question = question

        return super().form_valid(form)

django_quiz/views.py
# Django
from django.views.generic import TemplateView

class HomepageView(TemplateView):
    template_name = 'homepage.html'

django_quiz/templates/_account.html
{% if request.user.is_authenticated %}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
      role="button" aria-expanded="false">
        <span class="glyphicon glyphicon-user"></span> 
        {{ request.user }} <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li>
        <a href="#">
          <span class="glyphicon glyphicon-cog"></span> 
          Account
        </a>
      </li>
      <li>
        <a href="#">
          <span class="glyphicon glyphicon-log-out"></span> 
          Logout
        </a>
      </li>
    </ul>
  </li>
{% else %}
<li>
  <a href="#">
    <span class="glyphicon glyphicon-log-in"></span> 
    Login
  </a>
</li>
{% endif %}

django_quiz/templates/_head.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Quizzer">
<meta name="author" content="Some guy">

<title>{% block head_title %}Title{% endblock %}</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<style>
  div.spacer {
    margin-top: 100px;
  }
</style>

django_quiz/templates/_js_scripts.html
<script src="https://fb.me/react-0.13.3.js"></script>
<script src="https://fb.me/JSXTransformer-0.13.3.js"></script>
<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

django_quiz/templates/_navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" 
        data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Quizzer</a>
    </div><!-- .navbar-header -->

    <div class="collapse navbar-collapse" 
      id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="#">About</a>
        </li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#">
            <span class="glyphicon glyphicon-envelope"></span>
          </a>
        </li>
        {% include '_account.html' %}
      </ul>
    </div>
  </div><!-- .container -->
</nav>

django_quiz/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include '_head.html' %}
  </head>
  <body>
    {% block body %}
      {% block navbar %}
        {% include '_navbar.html' %}
      {% endblock %}

      {% block body_content %}
      {% endblock %}

      {% block js_scripts %}
        {% include '_js_scripts.html' %}
      {% endblock %}
    {% endblock %}
  </body>
</html>

django_quiz/templates/content/answers/templatetags/get_user_answer.html
{% if user_answer %}
<p>Your Answer: {{ user_answer }}</p>
  {% if user_answer.is_correct %}
    <p>Correct: <span class="glyphicon glyphicon-ok"></span></p>
  {% else %}
    <p>Wrong: <span class="glyphicon glyphicon-remove"></span></p>
  {% endif %}
{% endif %}

django_quiz/templates/content/lessons/detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="jumbotron">
      <h1>{{ object.title }}</h1>
    </div>

    <div class="col-sm-12">
      {{ object.body|linebreaks }}

      {% if object.quiz_set.count > 0 %}
      <div class="text-center">
        <h2>
          {% trans 'Understand the material? Take a quiz!' %}
        </h2>

        {% for quiz in object.quiz_set.all %}
        <a class="btn btn-primary btn-lg" 
          href="{{ quiz.get_absolute_url }}">
          {{ quiz.title }}
        </a>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div><!-- .row spacer -->
{% endblock %}

django_quiz/templates/content/lessons/list.html
{% extends 'base.html' %}

{% load i18n %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="jumbotron">
      <h1>Lessons</h1>
    </div>

    <div class="col-sm-12">
    {% if object_list %}
      {% for lesson in object_list %}
      <a href="{{ lesson.get_absolute_url }}">
        <div>
          <h2>{{ lesson.title }}</h2>
          <p>{{ lesson.body|truncatechars:150 }}</p>
          {% if lesson.tags.count > 0 %}
            <p>
            {% for tag in lesson.tags.all %}
              <span class="label label-info">{{ tag.name }}</span>
            {% endfor %}
            </p>
          {% endif %}
        </div>
      </a>
      {% endfor %}
    {% else %}
      <div class="alert alert-danger">
        <p>{% trans 'No lessons found.' %}</p>
      </div>
    {% endif %}
    </div>
  </div>
</div><!-- .row spacer -->
{% endblock %}

django_quiz/templates/content/questions/detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load content_tags %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="col-sm-12">
      <h1>Question</h1>

      <p class="lead">
        {{ object.body }}
      </p>

      {% if already_answered %}
        {% get_user_answer object request.user %}
      {% else %}
        <form action="{% url 'answer_create' object.id %}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-success btn-lg" type="submit">
            {% trans 'Confirm' %}
          </button>
        </form>
      {% endif %}
    </div>
  </div>
</div><!-- .row spacer -->
{% endblock %}

django_quiz/templates/content/quizzes/answers/list.html
{% extends 'base.html' %}

{% load i18n %}
{% load content_tags %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="jumbotron">
      <h1>Answers</h1>
      <p><strong>{% trans 'Score:' %}</strong> {{ score }}</p>
    </div>

    {% if object_list %}
    <div class="col-sm-12">
      <ol>
      {% for answer in object_list %}
        <li>
          <p>{{ answer.question.body }}</p>
          <p>Your Answer: {{ answer.choice }}</p>
          {% if answer.is_correct %}
            <p>Correct: <span class="glyphicon glyphicon-ok"></span></p>
          {% else %}
            <p>Wrong: <span class="glyphicon glyphicon-remove"></span></p>
          {% endif %}
        </li>
      {% endfor %}
      </ol>
    </div>
    {% else %}
    <div class="alert alert-danger">
      <p>{% trans 'No answers for this quiz' %}</p>
    </div>
    {% endif %}
  </div>
</div><!-- .row spacer -->
{% endblock %}

django_quiz/templates/content/quizzes/detail.html
{% extends 'base.html' %}

{% load i18n %}
{% load content_tags %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="jumbotron">
      <h1>{{ object.title }}</h1>
    </div>

    <div class="col-sm-12 text-center">
      {% if done %}
      <h2>See your results!</h2>
      <a class="btn btn-success btn-lg" 
        href="{% url 'quiz_answer_list' object.id %}">
        Review
      </a>
      {% else %}
      <h2>Ready to begin?</h2>
      <a class="btn btn-primary btn-lg" 
        href="{% url 'question_detail' object.question_set.first.id %}">
        Start quiz
      </a>
      {% endif %}
    </div>
  </div>
</div><!-- .row spacer -->
{% endblock %}

django_quiz/templates/homepage.html
{% extends 'base.html' %}

{% load i18n %}

{% block head_title %}{% trans 'Quizzer' %}{% endblock %}

{% block body_content %}
<div class="row spacer">
  <div class="container">
    <div class="jumbotron">
      <h1>QUIZZER</h1>
      <p>
      {% if request.user.is_authenticated %}
        <a class="btn btn-success btn-lg" href="{% url 'lesson_list' %}">
          {% trans 'Start Learning' %}
        </a>
      {% else %}
        <a class="btn btn-primary btn-lg" href="#">
          {% trans 'Login' %}
        </a>
      {% endif %}
      </p>
    </div>
  </div>
</div><!-- .row spacer -->
{% endblock %}